import Framework7 from './components/app/app-class';
import './components/accordion/accordion';
import './components/actions/actions';
import './components/autocomplete/autocomplete';
import './components/calendar/calendar';
import './components/data-table/data-table';
import './components/dialog/dialog';
import './components/form/form';
import './components/gauge/gauge';
import './components/grid/grid';
import './components/icon/icon';
import './components/infinite-scroll/infinite-scroll';
import './components/input/input';
import './components/lazy/lazy';
import './components/link/link';
import './components/list/list';
import './components/list-index/list-index';
import './components/login-screen/login-screen';
import './components/messagebar/messagebar';
import './components/messages/messages';
import './components/modal/modal';
import './components/navbar/navbar';
import './components/notification/notification';
import './components/page/page';
import './components/panel/panel';
import './components/photo-browser/photo-browser';
import './components/picker/picker';
import './components/popover/popover';
import './components/popup/popup';
import './components/preloader/preloader';
import './components/progressbar/progressbar';

export default Framework7;